---
name: merge-pulls

on:
  # schedule:
  #   - cron: "0 9 * * 1" # Weekdays at 9 AM UTC

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  merge-prs:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Merge Pull Requests # https://github.com/tagdots-dev/mb-test/
        id: merge-pull-request
        uses: tagdots-dev/mb-test@main
        env:
          GH_TOKEN: ${{ secrets.SECRET_PAT }}
        with:
          base-branch: main
          bypass-review-count: true
          dry-run: true
          exclude-labels: "do-not-merge,stale"
          include-labels: "automerge,dependencies"
          merge-method: merge
          owner: ""
          prefix: ""
          repo-type: all
